server:
  port: 8080

spring:
  aplication:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
          lower-case-service-id: true
        routes:
          - id: msAuthorization
            uri: http://localhost:8081
            predicates:
              - Path=/ouath**
          - id: msNotification
            uri: http://localhost:8081
            predicates:
              - Path=/ouath**
          - id: msProducts
            uri: http://localhost:8081
            predicates:
              - Path=/ouath**